### ISSUE TITLE
Complete newbie - trying to add Sony HDMI2 code to Broadlink RM4

### ISSUE THREAD

**Issue by dtewkesb** [mjg59/python-broadlink#323]
hey all, I'm relatively computer literate but this stuff is blowing my mind so would appreciate a dummies guide if possible.
I have a 2016 Sony bravia tv, and the remote only has a cycle through hdmi button.
I want to enter a specific code for hdmi2, 3, 4 etc.
How on earth do i to this please?
I've found a load of codes, just cant seem to work out how to get them onto the RM4.

any support much appreciated!

**Comment by felipediel** [comment]
Hello.

There are two approaches. One is to find the discrete codes on the internet. Sometimes you can find codes for HDMI1, HDMI2 etc.

The second option is to write a program that stores the state in a variable and cycles through the options until it gets in the position you asked for. There are many programs available for this. I recommend Home Assistant with SmartIR (you can also use the universal component).

Closing, since its not a problem to be fixed in our code base.
