### ISSUE TITLE
get_subdevices with RM4Pro

### ISSUE THREAD

**Issue by eadmaster** [mjg59/python-broadlink#800]
is it possible to read configured subdevices in the app with the RM4Pro?

I've tried with `device.get_subdevices()`, but the returned list is empty.

If possible this could bypass the need to [backup the learned codes from the app](https://github.com/mjg59/python-broadlink/issues/559).

**Comment by felipediel** [comment]
The term "subdevices" can be confusing because it has different meanings in this API and in the official Broadlink app. In the context of this API, "subdevices" refers to Broadlink devices connected to a master Broadlink device through a separate network interface. In the official Broadlink app, "subdevices" are virtual representations of IR/RF devices and their associated codes, which are stored in the cloud. That said, this API cannot access, manage, or interact with the cloud-stored "subdevices" from the Broadlink app.

**Comment by eadmaster** [comment]
> That said, this API cannot access, manage, or interact with the cloud-stored "subdevices" from the Broadlink app.

Do you know if there is a tool that can do that? the latest official Remote Control app has a "backup" feature, and it is also caching some data in `/storage/emulated/0/Android/data` (i'm trying to investigate these files if they contain something useful)

**Comment by felipediel** [comment]
Not that I know. I made a draft a few years ago, it worked, but I don't think I'll ever finish it.

Edit: Maybe I will finish, but I don't want people asking me when I will finish 😆

**Comment by iArtuc** [comment]
@eadmaster i'm curious if you solved the issue, i have the same issue, and trying to set the device state but failing
