### ISSUE TITLE
can't concat str to bytearray

### ISSUE THREAD

**Issue by GrexAut** [mjg59/python-broadlink#88]
Trying with python 3.5 to send:

device.send_data('260058000001279412131113123813121213111411141212123713371312113911391533133711381411121410141336121312141112131211391435133712121238123811381238130005240001274b11000c530001274a12000d05')
and I get the following message:
./send-bl.sh tvOn.txt
Connecting to Broadlink device....
Connected....
Traceback (most recent call last):
  File "./send-bl.sh", line 30, in <module>
    device.send_data('260058000001279412131113123813121213111411141212123713371312113911391533133711381411121410141336121312141112131211391435133712121238123811381238130005240001274b11000c530001274a12000d05');
  File "/share/MD0_DATA/smart_home/broadlink/broadlink/__init__.py", line 476, in send_data
    packet += data
TypeError: can't concat str to bytearray

**Comment by mob41** [comment]
Your data <code>260058000001279412131113123813121213111411141212123713371312113911391533133711381411121410141336121312141112131211391435133712121238123811381238130005240001274b11000c530001274a12000d05</code> is actually a HEX string. You have to convert it to a byte array instead of simply specifying it as a argument.

Try to use this: <code>bytearray.fromhex("260058000001279412131113123813121213111411141212123713371312113911391533133711381411121410141336121312141112131211391435133712121238123811381238130005240001274b11000c530001274a12000d05")</code>
